export enum MessageTemplate {
    WelcomeMessage = "welcome-message",
    WrongReply = "wrong-reply",

    RequestDriverDocument = "request-driver-document",
    RequestDriverDocumentConfirmation = "request-driver-document-confirmation",
    RequestDriverManualInfo = "request-driver-manual-info",
    RequestDriverManualInfoAgain = "request-driver-manual-info-again",
    RequestDriverManualInfoName = "request-driver-manual-info-name",
    
    DriverCreatedSuccessfully = "driver-created-successfully",
    AlreadyRegisteredAsADriver = "already-registered-as-a-driver",
    
    FirstPassengerWelcome = "first-passenger-welcome",

    DefaultDriverMessage = "default-driver-message",
    DefaultPassengerMessage = "default-passenger-message",

    TripRequestStart = "trip-request-start",
    TripRequestRejectionReply = "trip-request-rejection-reply",
    TripRequestStartConfirmed = "trip-request-start-confirmed",
    RequestCurrentLocation = "request-current-location",
    OrderCancelled = "order-cancelled",
    TripOverviewBeforeRequest = "trip-overview-before-request",
    PleaseWaitWhileSearchingDrivers = "please-wait-while-searching-drivers",
    PleaseWaitWhileSearchingDriversOnmessage = "please-wait-while-searching-drivers-onmessage",
    NewTripRequestAvailable = "new-trip-request-available",
    TripRequestNotPending = "trip-request-not-pending",
    DriverNotVerified = "driver-not-verified",
    DriverAlreadyOnTrip = "driver-already-on-trip",
    TripRequestNotFound = "trip-request-not-found",
    TripRequestAccepted = "trip-request-accepted",
    DriverTripOverview = "driver-trip-overview",
    TripRouteOverview = "trip-route-overview",
    WhatsappContactInfo = "whatsapp-contact-info",
    DriverArrivedNotification = "driver-arrived-notification",
    DriverArrivedAction = "driver-arrived-action",
    RequestTripCodeToDriver = "request-trip-code-to-driver",
    WrongTripCode = "wrong-trip-code",
    DriverEnRoadToDestinationAction = "driver-en-road-to-destination-action",
    TripCompletedDriver = "trip-completed-driver",
    TripCompletedCustomer = "trip-completed-customer",
    SendLocationHelp1 = "send-location-help-1",
    SendLocationHelp2 = "send-location-help-2",
    SendLocationHelp3 = "send-location-help-3",
    VerificationRequestNotAvailable = "verification-request-not-available",
    DriverAlreadyVerified = "driver-already-verified",
    DriverVerificationPrompt = "driver-verification-prompt",
    DriverVerificationRejectedInput = "driver-verification-rejected-input",
    DriverVerificationRejected = "driver-verification-rejected",
    DriverVerificationAccepted = "driver-verification-accepted",
    DefaultDriverReply = "default-driver-reply",
    DriverNotAllowedToChangeActiveStatus = "driver-not-allowed-to-change-active-status",
    DriverStatusToggleActive = "driver-status-toggle-active",
    DriverStatusToggleInactive = "driver-status-toggle-inactive",
    //* Message Templates
}